version: '3'
services:
  song_randomizer:
    build: .
    ports:
      - "4650:443"
    volumes:
      - certs:/certs
      - uploadedSongs:/app/uploads

volumes:
  certs:
  uploadedSongs: